version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo pre_build started on `date`
#      - gradle build
#      - mvn clean compile test
  build:
    commands:
      - echo build started on `date`
      - export BUCKET=codepipeline-us-west-1-720803681094
      - gradle build
#      - ./gradlew build
#      - mvn package shade:shade
#      - unzip build/libs/HelloWorldFunction.jar
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - echo build completed on `date` !!!
artifacts:
  files:
#    - build/libs/HelloWorldFunction.jar
    - template.yaml
    - outputtemplate.yaml